packages:
  - portfolio
  - recipes
  - common
onlyBuiltDependencies:
  - sharp
patchedDependencies:
  '@portaljs/remark-wiki-link': 'patches/@portaljs__remark-wiki-link.patch'
linkWorkspacePackages: true
